version: '3'

services:
  portfolio:
    build: portfolio
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USER_NAME: ${DB_USER_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on:
      portfolio_db:
        condition: service_healthy
  portfolio_db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: portfolio_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      
  
  
